### ISSUE TITLE
RuntimeError: file could not be found: 'mapquest_symbols/water.png'

### ISSUE THREAD

**Issue by noman377** [zachatrocity/mapnik-fork#2]
Zach, excellent article...was able to work through every step until "Generate an image!". Getting the following error. Any help is really appreciated. I am using Mapnik version 2.2.0 as I was not sure your exact version. Below is my cmd:

C:\RhinoTile\mapnik-fork>generate_image.py
Mapnik LOG> 2016-02-20 22:53:37: setting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2016-02-20 22:53:37: converting 'mode=normal' to 'comp-op:src_over'
Mapnik LOG> 2016-02-20 22:53:37: setting 'mode' is deprecated and will be removed in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2016-02-20 22:53:37: converting 'mode=normal' to 'comp-op:src_over'
Traceback (most recent call last):
  File "C:\RhinoTile\mapnik-fork\generate_image.py", line 43, in <module>
    mapnik.load_map(m,mapfile)
RuntimeError: file could not be found: 'mapquest_symbols/water.png' in style 'water_areas_lowzoom' in PolygonPatternSymbolizer at line 64 of 'mapquest-us.xml'

**Comment by noman377** [comment]
repo was missing mapquest_symbols folder and its assets. grabbed the same from the original mapquest fork and script is working perfect.

**Comment by zachatrocity** [comment]
Hey there, I got your email! Sorry I haven't responded yet. Was busy with school. Glad you got it working! If you need anything else let me know and I promise I'll be quicker to respond.

**Comment by noman377** [comment]
Za

**Comment by deanezra** [comment]
For anyone who is still finding that mapquest_symbols folder missing, the original github location to get the folder is here: https://github.com/MapQuest/MapQuest-Mapnik-Style

**Comment by zachatrocity** [comment]
Thanks for the link. I'll add it to the readme.
